# --- Data Settings ---
data:
  directory: "/gws/pw/j07/wio/WIOInterannual"

# --- Model Hyperparameters ---
hyperparameters:
  batch_size: 32
  learning_rate: 0.001

# --- Run Configuration ---
run:
  epochs: 100
  random_seed: 42